"""Pattern 2016: Instructions Based.

This pattern is handled by the moving_towards_direction generator.
The mapping is defined in generator.py _get_hybrid_type():
    'instructions based' -> 'moving_towards_direction'
"""


class InstructionsBasedMixin:
    """Mixin for instructions-based direction questions.

    Questions are generated by generate_moving_towards_direction via
    the MovingTowardsDirectionMixin.
    """
    pass
